debug: True

data_config:
  images_dir: "D:/Projects/clip_clf/data/Images/"
  image_size: 224
  captions_file: "D:/Projects/clip_clf/data/captions.txt"

training_config:
  batch_size: 8
  num_workers: 0
  lr: 0.001
  weight_decay: 0.001
  patience: 2
  factor: 0.5
  epochs: 5

model_config:
  image_model:
    model_name : 'resnet50'
    image_embedding : 2048
    pretrained : False
    trainable: False
  text_model:
    model_name : "distilbert-base-uncased"
    text_embedding : 768
    text_tokenizer : "distilbert-base-uncased"
    max_length : 200
    pretrained : False
    trainable : False
  temperature : 0.7
  num_projection_layers: 1
  projection_dim: 256
  dropout: 0.1